# -*- coding: utf-8 -*-
from . import functions
from . import profisc_auth
from . import profisc_actions
from . import models
from . import account_move_extension
from . import res_partner_extension
from . import account_payment_term_extension
from . import account_tax_extension
from . import res_users_extension
from . import res_company_extension
from . import uom_uom_extension
from . import pro_uoms
from . import hr_employee_extension
from . import pos_order_extension
from . import pos_order_wizard
from . import pos_config_extension
from . import pos_session_extension
from . import stock_picking_extension
from . import profisc_vehicles
from . import profisc_business_units
from . import profisc_tcr
from . import stock_warehouse_extension
from . import profisc_einvoice_profiles
from . import profisc_payment_methods
from . import pos_payment_method
from . import invoice_warranty
